/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CategoryStat { 'count' : bigint, 'category' : NoticeCategory }
export interface DayStat { 'date' : string, 'count' : bigint }
export interface Notice {
  'id' : NoticeId,
  'title' : string,
  'authorId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'fileLink' : [] | [string],
  'category' : NoticeCategory,
}
export type NoticeCategory = { 'Event' : null } |
  { 'Assignment' : null } |
  { 'Announcement' : null } |
  { 'Alert' : null };
export type NoticeId = bigint;
export interface NoticeInput {
  'title' : string,
  'date' : string,
  'description' : string,
  'fileLink' : [] | [string],
  'category' : NoticeCategory,
}
export interface NoticeStats {
  'perDay' : Array<DayStat>,
  'perCategory' : Array<CategoryStat>,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createNotice' : ActorMethod<[NoticeInput], Notice>,
  'deleteNotice' : ActorMethod<[NoticeId], boolean>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getNoticeStats' : ActorMethod<[], NoticeStats>,
  'getNoticesByCategory' : ActorMethod<[NoticeCategory], Array<Notice>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStudent' : ActorMethod<[], boolean>,
  'registerUserProfile' : ActorMethod<[string, string, UserRole], UserProfile>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchNotices' : ActorMethod<[string], Array<Notice>>,
  'updateNotice' : ActorMethod<[NoticeId, NoticeInput], [] | [Notice]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];