/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NoticeCategory = IDL.Variant({
  'Event' : IDL.Null,
  'Assignment' : IDL.Null,
  'Announcement' : IDL.Null,
  'Alert' : IDL.Null,
});
export const NoticeInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'fileLink' : IDL.Opt(IDL.Text),
  'category' : NoticeCategory,
});
export const NoticeId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Notice = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'authorId' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'fileLink' : IDL.Opt(IDL.Text),
  'category' : NoticeCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const DayStat = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const CategoryStat = IDL.Record({
  'count' : IDL.Nat,
  'category' : NoticeCategory,
});
export const NoticeStats = IDL.Record({
  'perDay' : IDL.Vec(DayStat),
  'perCategory' : IDL.Vec(CategoryStat),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createNotice' : IDL.Func([NoticeInput], [Notice], []),
  'deleteNotice' : IDL.Func([NoticeId], [IDL.Bool], []),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getNoticeStats' : IDL.Func([], [NoticeStats], ['query']),
  'getNoticesByCategory' : IDL.Func(
      [NoticeCategory],
      [IDL.Vec(Notice)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStudent' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole],
      [UserProfile],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchNotices' : IDL.Func([IDL.Text], [IDL.Vec(Notice)], ['query']),
  'updateNotice' : IDL.Func([NoticeId, NoticeInput], [IDL.Opt(Notice)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NoticeCategory = IDL.Variant({
    'Event' : IDL.Null,
    'Assignment' : IDL.Null,
    'Announcement' : IDL.Null,
    'Alert' : IDL.Null,
  });
  const NoticeInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'fileLink' : IDL.Opt(IDL.Text),
    'category' : NoticeCategory,
  });
  const NoticeId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Notice = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'authorId' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'fileLink' : IDL.Opt(IDL.Text),
    'category' : NoticeCategory,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const DayStat = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const CategoryStat = IDL.Record({
    'count' : IDL.Nat,
    'category' : NoticeCategory,
  });
  const NoticeStats = IDL.Record({
    'perDay' : IDL.Vec(DayStat),
    'perCategory' : IDL.Vec(CategoryStat),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createNotice' : IDL.Func([NoticeInput], [Notice], []),
    'deleteNotice' : IDL.Func([NoticeId], [IDL.Bool], []),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getNoticeStats' : IDL.Func([], [NoticeStats], ['query']),
    'getNoticesByCategory' : IDL.Func(
        [NoticeCategory],
        [IDL.Vec(Notice)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStudent' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole],
        [UserProfile],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchNotices' : IDL.Func([IDL.Text], [IDL.Vec(Notice)], ['query']),
    'updateNotice' : IDL.Func([NoticeId, NoticeInput], [IDL.Opt(Notice)], []),
  });
};

export const init = ({ IDL }) => { return []; };