/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface DayStat {
    date: string;
    count: bigint;
}
export interface CategoryStat {
    count: bigint;
    category: NoticeCategory;
}
export interface Notice {
    id: NoticeId;
    title: string;
    authorId: UserId;
    date: string;
    createdAt: Timestamp;
    description: string;
    fileLink?: string;
    category: NoticeCategory;
}
export type NoticeId = bigint;
export interface NoticeInput {
    title: string;
    date: string;
    description: string;
    fileLink?: string;
    category: NoticeCategory;
}
export interface UserProfile {
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export interface NoticeStats {
    perDay: Array<DayStat>;
    perCategory: Array<CategoryStat>;
}
export enum NoticeCategory {
    Event = "Event",
    Assignment = "Assignment",
    Announcement = "Announcement",
    Alert = "Alert"
}
export enum UserRole {
    admin = "admin",
    student = "student"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createNotice(input: NoticeInput): Promise<Notice>;
    deleteNotice(id: NoticeId): Promise<boolean>;
    getAllNotices(): Promise<Array<Notice>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getNoticeStats(): Promise<NoticeStats>;
    getNoticesByCategory(category: NoticeCategory): Promise<Array<Notice>>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStudent(): Promise<boolean>;
    registerUserProfile(name: string, email: string, role: UserRole): Promise<UserProfile>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchNotices(term: string): Promise<Array<Notice>>;
    updateNotice(id: NoticeId, input: NoticeInput): Promise<Notice | null>;
}
import type { CategoryStat as _CategoryStat, DayStat as _DayStat, Notice as _Notice, NoticeCategory as _NoticeCategory, NoticeId as _NoticeId, NoticeInput as _NoticeInput, NoticeStats as _NoticeStats, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createNotice(arg0: NoticeInput): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(to_candid_NoticeInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Notice_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(to_candid_NoticeInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Notice_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNotice(arg0: NoticeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async getAllNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoticeStats(): Promise<NoticeStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoticeStats();
                return from_candid_NoticeStats_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoticeStats();
            return from_candid_NoticeStats_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoticesByCategory(arg0: NoticeCategory): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoticesByCategory(to_candid_NoticeCategory_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoticesByCategory(to_candid_NoticeCategory_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStudent(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStudent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStudent();
            return result;
        }
    }
    async registerUserProfile(arg0: string, arg1: string, arg2: UserRole): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUserProfile(arg0, arg1, to_candid_UserRole_n25(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserProfile_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUserProfile(arg0, arg1, to_candid_UserRole_n25(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserProfile_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchNotices(arg0: string): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNotices(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNotices(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNotice(arg0: NoticeId, arg1: NoticeInput): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(arg0, to_candid_NoticeInput_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(arg0, to_candid_NoticeInput_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CategoryStat_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryStat): CategoryStat {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeCategory): NoticeCategory {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeStats_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeStats): NoticeStats {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Notice_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notice): Notice {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Notice | null {
    return value.length === 0 ? null : from_candid_Notice_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n16(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    perDay: Array<_DayStat>;
    perCategory: Array<_CategoryStat>;
}): {
    perDay: Array<DayStat>;
    perCategory: Array<CategoryStat>;
} {
    return {
        perDay: value.perDay,
        perCategory: from_candid_vec_n22(_uploadFile, _downloadFile, value.perCategory)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    category: _NoticeCategory;
}): {
    count: bigint;
    category: NoticeCategory;
} {
    return {
        count: value.count,
        category: from_candid_NoticeCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoticeId;
    title: string;
    authorId: _UserId;
    date: string;
    createdAt: _Timestamp;
    description: string;
    fileLink: [] | [string];
    category: _NoticeCategory;
}): {
    id: NoticeId;
    title: string;
    authorId: UserId;
    date: string;
    createdAt: Timestamp;
    description: string;
    fileLink?: string;
    category: NoticeCategory;
} {
    return {
        id: value.id,
        title: value.title,
        authorId: value.authorId,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        fileLink: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.fileLink)),
        category: from_candid_NoticeCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Event: null;
} | {
    Assignment: null;
} | {
    Announcement: null;
} | {
    Alert: null;
}): NoticeCategory {
    return "Event" in value ? NoticeCategory.Event : "Assignment" in value ? NoticeCategory.Assignment : "Announcement" in value ? NoticeCategory.Announcement : "Alert" in value ? NoticeCategory.Alert : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    student: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "student" in value ? UserRole.student : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notice>): Array<Notice> {
    return value.map((x)=>from_candid_Notice_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryStat>): Array<CategoryStat> {
    return value.map((x)=>from_candid_CategoryStat_n23(_uploadFile, _downloadFile, x));
}
function to_candid_NoticeCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeCategory): _NoticeCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_NoticeInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeInput): _NoticeInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}): {
    principal: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n25(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    description: string;
    fileLink?: string;
    category: NoticeCategory;
}): {
    title: string;
    date: string;
    description: string;
    fileLink: [] | [string];
    category: _NoticeCategory;
} {
    return {
        title: value.title,
        date: value.date,
        description: value.description,
        fileLink: value.fileLink ? candid_some(value.fileLink) : candid_none(),
        category: to_candid_NoticeCategory_n5(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    student: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.student ? {
        student: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeCategory): {
    Event: null;
} | {
    Assignment: null;
} | {
    Announcement: null;
} | {
    Alert: null;
} {
    return value == NoticeCategory.Event ? {
        Event: null
    } : value == NoticeCategory.Assignment ? {
        Assignment: null
    } : value == NoticeCategory.Announcement ? {
        Announcement: null
    } : value == NoticeCategory.Alert ? {
        Alert: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
